# Generated by Django 4.0.1 on 2022-01-28 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancecompany',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
